config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/users" => "home#users"
  post "/users" => "home#users"

  resources :results, only: [:index] do
    collection {get :winner_users}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'httparty'

  def index
  end

  def users
    @user1 = []
    @user2 = []
    begin
      response_user1 = GitUsers.build!(params[:home][:name1])
      response_user1 = JSON.parse(response_user1.body)
      if response_user1["message"] == nil
        response_user2 = GitUsers.build!(params[:home][:name2])
        response_user2 = JSON.parse(response_user2.body)
        if response_user2["message"] == nil
          @user1 = response_user1
          @user2 = response_user2
        else
          flash[:warning] = "User 2 dont't exist"
          redirect_to root_path
        end
      else
        flash[:warning] = "User 1 dont't exist"
        redirect_to root_path
      end
    rescue Exception => error
      flash[:danger] = "Make try later"
      redirect_to root_path
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def winner_users
    # begin
    #   response_repos1 = GetRepos.build!(params["user1"])
    #   response_repos1 = JSON.parse(response_repos1.body)
    #   response_repos2 = GetRepos.build!(params["user2"])
    #   response_repos2 = JSON.parse(response_repos2.body)
    #   @results_winner = SearchWinner.build!(response_repos1, response_repos2)
    @results_winner = {:response1=>[{:name=>"sm-liy", :stars=>0}], :response2=>[{:name=>"restaurant365", :stars=>0}, {:name=>"pin-pon-master", :stars=>0}, {:name=>"panel_rh", :stars=>0}, {:name=>"dashboard", :stars=>2}, {:name=>"api-rh", :stars=>2}], :stars_user1=>0, :stars_user2=>4, :name_user1=>"Fernando420", :name_user2=>"torvick", :avatar_user1=>"https://avatars3.githubusercontent.com/u/29613794?v=4", :avatar_user2=>"https://avatars3.githubusercontent.com/u/43286336?v=4"}
    # rescue Exception => error
    #   flash[:danger] = "Make try later"
    #   redirect_to root_path()
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-login">
        <div class="panel-heading">
          <div class="row">
            <h4 align="center">Enter names of github users</h4>
          </div>
          <hr>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-12">
              <%= form_for :home, url: users_path do |f| %>
                <div class="form-group">
                  <%= f.text_field :name1, autofocus: true, :class => "form-control", :placeholder => "Name user 1", required: true%>
                </div>
                <div class="form-group">
                  <%= f.text_field :name2, autofocus: true, :class => "form-control", :placeholder => "Name user 1", required: true%>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                      <%= f.submit "Start!", class: "form-control btn btn-login", data: {disable_with: "Processing..."} %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/users.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-login">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-6">
              <a href="#" class="active" id="users1">User 1</a>
            </div>
            <div class="col-xs-6">
              <a href="#" id="users2">User 2</a>
            </div>
          </div>
          <hr>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-12">
              <div id="user1" style="display: block;">
                <div align="center" class="col-lg-3 col-md-3 col-sm-3">
                  <img src="<%= @user1["avatar_url"] %>" alt="user1" class="img-circle" width="100" height="100">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                  <ul>
                    <li>
                      <labe>ID: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp <%= @user1["id"] %></labe>
                    </li>
                  </ul>
                  <ul>
                    <li>
                      <labe>User: &nbsp <%= @user1["login"] %></labe>
                    </li>
                  </ul>
                </div>
              </div>
              <div id="user2" style="display: none;">
                <div align="center" class="col-lg-3 col-md-3 col-sm-3">
                  <img src="<%= @user2["avatar_url"] %>" alt="user1" class="img-circle" width="100" height="100">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                  <ul>
                    <li>
                      <labe>ID: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp <%= @user2["id"] %></labe>
                    </li>
                  </ul>
                  <ul>
                    <li>
                      <labe>User: &nbsp <%= @user2["login"] %></labe>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div align="center" class="col-lg-12 col-md-12 col-sm-12">
              <%= link_to "Winner?", winner_users_results_path(user1: @user1["login"], user2: @user2["login"]), :class => "btn btn-primary btn-lg", data: {disable_with: "Processing..."} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >Konsigue</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Enter names of new users</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notifications.html.erb
<% if flash[:alert] %>
  <div class="alert alert-success alertt">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= flash[:alert] %>!</strong>
  </div>
<% end %>
<% if flash[:danger] %>
  <div class="alert alert-danger alertt">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= flash[:danger] %>!</strong>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success alertt">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= flash[:notice] %>!</strong>
  </div>
<% end %>
<% if flash[:successfully] %>
  <div class="alert alert-success alertt">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= flash[:successfully] %>!</strong>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert alert-warning alertt">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= flash[:warning] %>!</strong>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konsigue</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>

</head>

<body>

<%= render 'layouts/navigation' %>


<div class="container">
  <%= render 'layouts/notifications' %>

  <%= yield %>
</div>
</body>
</html>

app/views/results/winner_users.html.erb
<div class="body_color">
  <div class="container">
    <div class="card person-card">
      <div class="card-body">
        <!-- Sex image -->
        <% if @results_winner[:stars_user1] > @results_winner[:stars_user2] %>
          <img id="img_sex" class="person-img" src="<%= @results_winner[:avatar_user1] %>">
          <h2 id="winner_user" class="card-title">Winner <%= @results_winner[:name_user1] %></h2>
          <h3 id="winner_user" class="card-title">Stars <i class="glyphicon glyphicon-star"></i> <%= @results_winner[:stars_user1] %></h3>
        <% else %>
          <img id="img_sex" class="person-img" src="<%= @results_winner[:avatar_user2] %>">
          <h2 id="winner_user" class="card-title">Winner <%= @results_winner[:name_user2] %></h2>
          <h3 id="winner_user" class="card-title">Stars <i class="glyphicon glyphicon-star"></i> <%= @results_winner[:stars_user2] %></h3>
      <% end %>
        <!-- First row (on medium screen) -->
        <div class="row">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6" style="padding: 0.5em;">
        <div class="card">
          <div class="card-body">
            <h2 align="center" class="card-title"><%= @results_winner[:name_user1] %></h2>
            <table id="datatable" class="table table-striped">
              <thead class="thead-blue">
              <tr>
                <th class="font-white">Name Repo</th>
                <th class="font-white">Stars Repo</th>
              </tr>
              </thead>

              <tbody>

              <% @results_winner[:response1].each do |repo| %>
                <tr>
                  <td><%= repo[:name] %></td>
                  <td><%= repo[:stars] %></td>
                </tr>
              <% end %>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 align="center" class="card-title"><%= @results_winner[:name_user2] %></h2>
            <table id="datatable1" class="table-responsive table table-striped">
              <thead class="thead-blue">
              <tr>
                <th class="font-white">Name Repo</th>
                <th class="font-white">Stars Repo</th>
              </tr>
              </thead>

              <tbody>

              <% @results_winner[:response2].each do |repo| %>
                <tr>
                  <td><%= repo[:name] %></td>
                  <td><%= repo[:stars] %></td>
                </tr>
              <% end %>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>